extractRS:
	@python image_features_extractor.py --imgPath ../DB/imgRS --resultPath ../DB/featureRS --identity $(ID)
	
extractFD:
	@python image_features_extractor.py --imgPath ../DB/imgFD --resultPath ../DB/featureFD --identity $(ID)
